server:
  port: 9527

spring:
  application:
    name: cloud-gateway # 服务名称
  cloud: # 配置网关
    gateway:
      routes: # 配置路由信息
        # 断言1
        - id: payment_routh # payment_routh 路由的id,没有固定规则但是要求唯一,建议配合服务名
          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          predicate:
            - Path=/payment/get/** # 断言,路径相匹配的进行路由
        # 断言2
        - id: payment_routh2 # payment_routh2 路由的id,没有固定规则但是要求唯一,建议配合服务名
          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          predicate:
            - Path=/payment/lb/** # 断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service # Eureka实例名称
  client:
      register-with-eureka: true # 是否将自己注册进注册中心
      fetch-registry: true # 是否从注册中心检索服务
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka # 单机版