server:
  port: 80

spring:
  application:
    name: cloud-consumerzk-order
  cloud:
  # 注册到zookeeper地址
    zookeeper:
      connect-string: localhost:${server.port} # 注册中心地址

#调用的服务名称
zookeeper:
  provider:
    payment: http://cloud-proivder-payment