server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      dafaultZooe: http://eureka7001.com:7001/eureka # 单机环境
      #dafaultZooe: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群环境

ribbon: # 设置OpenFeign客户端超时时间(OpenFeign默认支持Ribbon)
  ReadTimeOut: 5000 # 消费者和服务者之间的连接等待时间,超时报错 单位为毫秒
  ConnectTimeout: 5000 # 发送请求获取数据等待时间,超时报错 单位为毫秒

feign:
  hystrix: # 客户端配置服务降级
    enabled: true # 启动配置